### ISSUE TITLE
Add a command to return the version of the CLI

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#146] opened 2017-11-22 03:01 UTC
@cfjedimaster commented on [Fri Dec 23 2016](https://github.com/apache/incubator-openwhisk/issues/1677)

There is no available command to `wsk` that returns the version of the CLI installed.

---

@rabbah commented on [Fri Dec 23 2016](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-269040753)

Try: `wsk property get -h`

---

@cfjedimaster commented on [Fri Dec 23 2016](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-269040900)

Confirmed this works: wsk property get --cliversion

However, this should be exposed on the top level help screen. It is a pretty common feature (imo) should be made more evident.

---

@rabbah commented on [Thu Jan 05 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-270570573)

Sure `wsk --version` makes sense as an alias.

---

@dubeejw commented on [Wed Jan 11 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-271895914)

Looks like there is two different converstations going on here. One about the wsk CLI and the other about wskdeploy.

---

@rabbah commented on [Wed Jan 11 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-271896806)

This issue should address `wsk` not `wsk deploy`.

---

@lzbj commented on [Mon Jan 16 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-272778883)

@rabbah, is this one we need fix or not? 

---

@rabbah commented on [Mon Jan 16 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-272848477)

We should add wsk --version and it would be great to also add an auto update feature as well or at least notify the user there is a newer version. 

---

@markusthoemmes commented on [Mon Jan 16 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-272856232)

We'll need to improve our build processes to not create a new CLI version if no code has changes, as the CLI is currently versioned by date and you don't want to notify users everytime a new OpenWhisk is deployed.

---

@rabbah commented on [Mon Jan 16 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-272857729)

Agree - the date was more intended to show the build date, not the actual version. We could adopt semantic versioning and do it manually to get going.

---

@lzbj commented on [Mon Jan 16 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-273010095)

manually you mean we pass in build number as arguments everytime we updated code?

---

@dubeejw commented on [Tue Jan 17 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-273174535)

A new CLI is not created if the code has not been changed as long as there is already a Docker container of the built CLI in the cache.

---

@lzbj commented on [Thu Jan 19 2017](https://github.com/apache/incubator-openwhisk/issues/1677#issuecomment-273700696)

Ok, got it.

**Comment by rabbah** [comment] 2019-02-14 15:48
Closing as duplicate of https://github.com/apache/incubator-openwhisk-cli/issues/136.

**Closed by rabbah** 2019-02-14 15:48 UTC
Labels: enhancement
